deluge-vpn:
  dns:
    enabled: false
  network:
    internal: true
    service_port: 8112
    networks:
      - name: "br1"
        ip_address: "192.168.5.28"
  auth:
    enabled: false
    group: "Arr"
  secrets:
    VPN_USER: "VPN_USER" 
    VPN_PASS: "VPN_PASS" 
  icon: "https://vectorified.com/images/deluge-icon-3.jpg"
  service_name: "deluge-vpn"
  image_name: "binhex/arch-delugevpn:2.2"
  mounts:
    - "/etc/localtime:/etc/localtime:ro"
    - "/mnt/user/Arr/deluge-data:/config"
    - "/mnt/user/Downloads:/data/downloads"
    - "/mnt/user/Arr/deluge-data/openvpn:/config/openvpn"
  capabilities:
    add:
      - "CAP_NET_ADMIN"
  env:
    - "TZ=America/Chicago"
    - "ENABLE_SOCKS=no"
    - "STRICT_PORT_FORWARD=yes"
    - "DEBUG=false"
    - "ENABLE_PRIVOXY=no"
    - "PGID=100"
    - "PUID=1000"
    - "VPN_ENABLED=yes"
    - "VPN_PROV=custom"
    - "VPN_CLIENT=openvpn"
    - "LAN_NETWORK=192.168.1.0/24"
    - "UPDATE_VAL=1"