mysql3:
  host: "net1"
  dns:
    enabled: false
    internal: true
  network_mode: "host"
  auth:
    enabled: false
  secrets:
    MYSQL_ROOT_PASSWORD: "tower_mysql_root_pwd_temp" 
    MYSQL_DATABASE: "tower_mysql_db_temp" 
    MYSQL_USER: "tower_mysql_user_temp" 
    MYSQL_PASSWORD: "tower_mysql_pass_temp" 
  service_name: "mysql-net1"
  image_name: "mysql"
  mounts:
    - "/etc/localtime:/etc/localtime:ro"