postgres:
  dns:
    enabled: false
  network:
    internal: true
    service_port: 5432
    networks:
      - name: "br1"
        ip_address: "192.168.4.105"
  auth:
    enabled: false
  secrets:
    POSTGRES_USER: "POSTGRES_USER" 
    POSTGRES_PASSWORD: "POSTGRES_PASSWORD" 
    POSTGRES_DB: "POSTGRES_DB" 
  service_name: "postgres_db"
  image_name: "postgres:14"
  mounts:
    - "/etc/localtime:/etc/localtime:ro"
    - "/mnt/user/DataStore/postgres-data:/var/lib/postgresql/data"