redis:
  dns:
    enabled: false
  network:
    internal: true
    service_port: 6379
    networks:
      - name: "br1"
        ip_address: "192.168.4.116"
  auth:
    enabled: false
  secrets:
    REDIS_PASSWORD: "tower_redis_password" 
  service_name: "redis"
  image_name: "redis:alpine"
  mounts:
    - "/etc/localtime:/etc/localtime:ro"
    - "/mnt/user/DataStore/redis-data:/data"
  commands:
    - "/bin/sh"
    - "-c"
    - "redis-server --appendonly yes --requirepass \"$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}\""