requestrr:
  dns:
    enabled: false
  network:
    internal: true
    service_port: 4545
    networks:
      - name: "br1"
        ip_address: "192.168.5.27"
  auth:
    enabled: false
  service_name: "requestrr"
  image_name: "darkalfx/requestrr:v2.1.3"
  mounts:
    - "/mnt/user/Arr/requestrr-data:/config"
    - "/etc/localtime:/etc/localtime:ro"