wordpress:
  dns:
    enabled: true
    domain_name: "wordpress.mallett.family"
    internal: false
  network:
    internal: false
    service_port: 80
    networks:
      - name: "br1"
        ip_address: "192.168.5.82"
  auth:
    enabled: false
  env:
    - "WORDPRESS_DB_HOST=192.168.5.83"
  secrets:
    WORDPRESS_DB_USER: "tower_mysql_user_temp" 
    WORDPRESS_DB_PASSWORD: "tower_mysql_pass_temp" 
    WORDPRESS_DB_NAME: "tower_mysql_db_temp" 
  service_name: "wordpress"
  image_name: "wordpress"
  mounts:
    - "/etc/localtime:/etc/localtime:ro"