---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Mallett Home
background: 
  image: https://images.unsplash.com/photo-1633901605644-e7f62844a460?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=joran-quinten-DsYEzIC_cSk-unsplash.jpg&w=2400
  #blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 75 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100
cardBlur: xs
theme: dark
color: slate
layout:
  Arrrr:
    style: row
    columns: 4
headerStyle: boxed
target: _blank
hideVersion: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: google # google, duckduckgo, bing, baidu, brave or custom
showStats: true