  arr_services:
    env:
      - "PUID=1000"
      - "PGID=100"
      - "TZ=America/Chicago"
    mounts:
      - "/etc/localtime:/etc/localtime:ro"
      - "/mnt/user/Media:/media"
      - "/mnt/user/Downloads:/downloads"
    services:
      prowlarr:
        internal: true
        icon: "https://static-00.iconduck.com/assets.00/prowlarr-icon-512x512-v9ekdjxx.png"
        service_name: "prowlarr"
        service_port: 9696
        image_name: "linuxserver/prowlarr:1.37.0"
        domain_name: "prowlarr.dcapi.app"
        ip_address: "192.168.5.22"
        mounts:
          - "/mnt/user/Arr/prowlarr-data:/config"
      sonarr:
        internal: true
        icon: "https://static-00.iconduck.com/assets.00/sonarr-icon-1024x1024-wkay604k.png"
        service_name: "sonarr"
        service_port: 8989
        image_name: "linuxserver/sonarr:4.0.14.2939-ls281"
        domain_name: "sonarr.dcapi.app"
        ip_address: "192.168.5.23"
        mounts:
          - "/mnt/user/Arr/sonarr-data:/config"
      radarr:
        internal: true
        icon: "https://static-00.iconduck.com/assets.00/radarr-icon-462x512-bydv4e4f.png"
        service_name: "radarr"
        service_port: 7878
        image_name: "linuxserver/radarr:5.26.2"
        domain_name: "radarr.dcapi.app"
        ip_address: "192.168.5.24"
        mounts:
          - "/mnt/user/Arr/radarr-data:/config"
      lidarr: 
        internal: true
        service_name: "lidarr" 
        service_port: 8686
        image_name: "linuxserver/lidarr:2.13.0-develop"
        domain_name: "lidarr.dcapi.app"
        ip_address: "192.168.5.25"
        mounts:
          - "/mnt/user/Arr/lidarr-data:/config"
      readarr:
        internal: true
        service_name: "readarr"
        service_port: 8787
        image_name: "linuxserver/readarr:0.4.17-develop"
        domain_name: "readarr.dcapi.app"
        ip_address: "192.168.5.26"
        mounts:
          - "/mnt/user/Arr/readarr-data:/config"