karakeep:
  zone_name: "mallett.family"
  env:
  mounts:
  generated_secrets:
    - "NEXTAUTH_SECRET"
  networks:
    karakeep:
      internal: true
  services:
    karakeep:
        dns:
          enabled: true
          domain_name: "keep.mallett.family"
        network:
          internal: false
          service_port: 3000
          networks:
            - name: "karakeep"
            - name: "br1"
              ip_address: "192.168.5.241"
        auth:
          enabled: true
          group: "Productivity"
          oauth: 
            enabled: true
            keys:
              OAUTH_CLIENT_ID: "client_id"
              OAUTH_CLIENT_SECRET: "client_secret"
              OAUTH_WELLKNOWN_URL: "well_known_url"
            redirect_uris:
              - "api/auth/callback/custom"
            scopes:
              - "openid"
              - "email"
              - "profile"
        icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/karakeep.png"
        service_name: "karakeep"
        description: "Karakeep is an open source \"Bookmark Everything\" app that uses AI for automatically tagging the content you throw at it. The app is built with self-hosting as a first class citizen."
        image_name: "ghcr.io/karakeep-app/karakeep:0.25.0"
        env:
          - "MEILI_ADDR=http://meillisearch:7700"
          - "BROWSER_WEB_URL=http://chrome:9222"
          - "NEXTAUTH_SECRET=${NEXTAUTH_SECRET}"
          - "NEXTAUTH_URL=https://keep.mallett.family"
          - "DISABLE_SIGNUPS=false"
          - "DISABLE_PASSWORD_AUTH=true"
          - "OAUTH_PROVIDER_NAME=Authentik"
          - "OAUTH_SCOPE=openid email profile"
          - "OAUTH_TIMEOUT=3500"
          - "DATA_DIR=/data"
        mounts:
          - "/mnt/user/DataStore/karakeep/data:/data"
    meillisearch:
        dns: 
          enabled: false
        network:
          internal: true
          networks:
            - name: "karakeep"
        auth:
          enabled: false
        icon: "https://static-00.iconduck.com/assets.00/search-icon-512x512-dlh8ei42.png"
        service_name: "meillisearch"
        image_name: "getmeili/meilisearch:v1.13.3"
        mounts:
          - "/mnt/user/DataStore/meili/data:/meili_data"
        networks:
          - "karakeep-internal"
        env:
          - "MEILI_NO_ANALYTICS=true"
          - "NEXTAUTH_SECRET=${NEXTAUTH_SECRET}"
          - "NEXTAUTH_URL=http://karakeep:3000"
          #- "MEILI_MASTER_KEY=${MEILI_MASTER_KEY}"
    chrome:
        dns:  
          enabled: false
        network:
          internal: true
          networks:
            - name: "karakeep"
            - name: "bridge"
        auth:
          enabled: false
        icon: "https://static-00.iconduck.com/assets.00/chrome-icon-512x512-5ln6wbyk.png"
        service_name: "chrome"
        network_mode: "bridge"
        image_name: "gcr.io/zenika-hub/alpine-chrome:123"
        commands:
          - "--no-sandbox"
          - "--disable-gpu"
          - "--disable-dev-shm-usage"
          - "--remote-debugging-address=0.0.0.0"
          - "--remote-debugging-port=9222"
          - "--hide-scrollbars"