name: Terraform Apply

on:
  push:
    branches:
      - main 
    paths-ignore:
      - .github/workflows/run-apply.yml
      - .github/workflows/run-plan.yml
      - ReadMe.md
      - .gitignore
  workflow_dispatch: #
    inputs:
      tfc_run_id:
        description: 'Optional: Terraform Cloud Run ID to apply. If left empty, a new run will be created.'
        required: false
        type: string

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Trigger Terraform Cloud Apply Plan
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        id: create-run
        if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && (github.event.inputs.tfc_run_id == '' || github.event.inputs.tfc_run_id == null)) }}
        with:
          token: ${{ secrets.TF_API_TOKEN }}
          hostname: app.terraform.io 
          organization: ${{ secrets.TF_ORGANIZATION }} 
          workspace: ${{ secrets.TF_WORKSPACE }} 
          message: "Triggered by push to main: ${{ github.sha }}"
          is_destroy: false 

      - name: Check Terraform Cloud Run Status
        if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && (github.event.inputs.tfc_run_id == '' || github.event.inputs.tfc_run_id == null)) }}
        run: |
          echo "Terraform Cloud Plan ID: ${{ steps.create-run.outputs.run_id }}"
          echo "Terraform Cloud Plan URL: ${{ steps.create-run.outputs.run_url }}"

      - name: Run Plan
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        id: apply
        continue-on-error: true
        with:
            hostname: app.terraform.io
            token: ${{ secrets.TF_API_TOKEN }} 
            run: ${{ github.event.inputs.tfc_run_id || steps.create-run.outputs.run_id }}
            comment: "Confirmed from GitHub Actions CI"

      - name: Check Terraform Cloud Run Status
        run: |
          echo "Terraform Cloud Apply ID: ${{ steps.apply.outputs.run_id }}"
          echo "Terraform Cloud Apply URL: ${{ steps.apply.outputs.run_link }}"
