name: Terraform Apply

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/run-apply.yml'
      - '.github/workflows/run-plan.yml'
      - './ReadMe.md'
      - './.gitignore'
      - './docs/*'
  workflow_dispatch:

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      max-parallel: 1
      matrix:
        include:
          - name: core
            workspace_secret: TF_WORKSPACE_CORE
          - name: apps
            workspace_secret: TF_WORKSPACE_APPS
    env:
        TF_WORKSPACE: ${{ secrets[matrix.workspace_secret] }}
        CONFIG_DIRECTORY: "./"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        id: upload-configuration
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}
          token: ${{ secrets.TF_API_TOKEN }}
          organization: ${{ secrets.TF_ORGANIZATION }}

      - name: Trigger Terraform Cloud Apply
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        id: create-run
        with:
          token: ${{ secrets.TF_API_TOKEN }}
          hostname: app.terraform.io
          organization: ${{ secrets.TF_ORGANIZATION }}
          workspace: ${{ env.TF_WORKSPACE }}
          message: "Triggered by push to main (${{ matrix.name }}): ${{ github.sha }}"
          is_destroy: false

      - name: Apply Run
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        id: apply
        with:
            hostname: app.terraform.io
            token: ${{ secrets.TF_API_TOKEN }}
            run: ${{ steps.create-run.outputs.run_id }}
            comment: "Confirmed from GitHub Actions CI (${{ matrix.name }})"

      - name: Check Terraform Cloud Run Status
        run: |
          echo "Terraform Cloud Apply ID: ${{ steps.apply.outputs.run_id }}"
          echo "Terraform Cloud Apply URL: ${{ steps.apply.outputs.run_link }}"
